name: Issue to Hexo
on:
  issues:
    # Sufficient to trigger this workflow when an issue is unlabeled, labeled, edited, milestoned
    types: [unlabeled, labeled, edited, milestoned]
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.actor == github.repository_owner }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'    
      - uses: zenghongtu/github-issue-to-hexo@v2.0.0
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './public'

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true   
